### ISSUE TITLE
Write a ERD for issue #72 (RBAC) 

### ISSUE THREAD

**Issue by utsab** [freeCodeCamp/classroom#112]
Write down a proposal for what changes we should introduce into the codebase: 
- Are we changing any existing models?  Creating new models? 
- Will we have 1 button that supports both the sign-in and sign-up functionality, or split up the behavior into separate buttons? 
- Are we creating any new pages, classes, controllers?

**Comment by computingtalentinitiative** [comment]
This was completed.  Here is the [ERD](https://docs.google.com/document/u/1/d/1EVn3N94Svi_d1Acdd3k9WcVOQvfCieXY4GxOQ2veNPw/edit?pli=1)

**Comment by utsab** [comment]
ERD is located [here](https://docs.google.com/document/u/1/d/1EVn3N94Svi_d1Acdd3k9WcVOQvfCieXY4GxOQ2veNPw/edit?pli=1).
