### ISSUE TITLE
Authenticate all API endpoints

### ISSUE THREAD

**Issue by utsab** [freeCodeCamp/classroom#116]
Most of the API endpoints are not secure.  We should add checks to ensure that only authorized users have access to specific endpoints.  Take a look at this [file](https://github.com/freeCodeCamp/classroom/pull/117/files#diff-5d89fa49bedc90b694bb6d0d632d3622b6ca948548cfd3cd4cb901815138660e)

**Comment by Ankit5kumar** [comment]
How I contribute to this project.Please let me know

**Comment by utsab** [comment]
Assigning this issue to @st3phy831

**Comment by Ankit5kumar** [comment]
Ok ,
Please let me know Specifically node js project to contribute for backend.
