### ISSUE TITLE
Improve setup process for new contributors: 

### ISSUE THREAD

**Issue by utsab** [freeCodeCamp/classroom#138]
Currently we give contributors the credentials (not ideal because we want to keep these private) 
Solution 1: Add instructions for how contributors can create their own Auth0 credentials (not ideal because it may too daunting/complex). Or maybe this is manageable?  Let's investigate.  
Solution 2: Create a Dev Log-in setup (simpler than Auth0)

**Comment by GuillermoFloresV** [comment]
The current solutions for this have been addressed by #153 or with this [guide](https://docs.google.com/document/d/1apfjzfIwDAfg6QQf2KD1E1aeD-KU7DEllwnH9Levq4A/) for local (no GitPod) development.
