### ISSUE TITLE
Update package.json to specify the correct version of react (and another dependencies) 

### ISSUE THREAD

**Issue by utsab** [freeCodeCamp/classroom#148]
See Mrugesh's [comment](https://github.com/freeCodeCamp/classroom/pull/146#pullrequestreview-1143159304). 

Instead of documenting the correct react version numbers in the README.md, let's pin the versions in the package.json. 

Dependabot may be continually updating the package.json with the latest version numbers of all libraries.  We may need to somehow disable /modify the behavior of dependabot so that we can pin the version numbers.

**Comment by GuillermoFloresV** [comment]
Closed with #230
