### ISSUE TITLE
2 warning messages at the terminal

### ISSUE THREAD

**Issue by fahsujitra** [freeCodeCamp/classroom#154]
There are 2 warning messages at the terminal while running, clearing these warnings could help a developer to see new error/warning messages easier.

1. Warning: Received `true` for a non-boolean attribute `crossOrigin`.
This one is from next.js google font loading

2. [next-auth][warn][NO_SECRET]
This one is from next-auth.js and warns about no defined random string secret for hashing tokens, sign/encrypt cookies
REF. https://next-auth.js.org/configuration/options#secret

**To Reproduce**
run `npm run develop`

**Expected behavior**
no warnings, clearly logging messages at the terminal

**Screenshots**
```
Warning: Received `true` for a non-boolean attribute `crossOrigin`.

If you want to write it to the DOM, pass a string instead: crossOrigin="true" or crossOrigin={value.toString()}.
    at link
    at head
    at Head (webpack-internal:///./node_modules/next/dist/pages/_document.js:239:1)
    at html
    at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:204:73)
    at MyDocument (webpack-internal:///./pages/_document.js:11:1)
[next-auth][warn][NO_SECRET] 
https://next-auth.js.org/warnings#no_secret
```

**Comment by fahsujitra** [comment]
It would be great if the maintainer could let me create a PR for this issue

**Comment by utsab** [comment]
@fahsujitra Sure, you're welcome to submit a PR for this.  Thanks for filing the issue.
