### ISSUE TITLE
Add red/yellow/green color codes for each student in the classroom

### ISSUE THREAD

**Issue by utsab** [freeCodeCamp/classroom#172]
We would like to add a red/yellow/green label to each student on the dashboard page for the classroom.  The red-zone students are least enaged; green-zone students are most engaged.  

TODO: We will post a design mock-up showing what the new UI should look like with the color codes.  Or, if any contributors want to propose a mock-up, please do so.  

Level 2: consider adding filtering functionality so that the Teacher can quickly select the students who are in the red-zone or yellow/green zones.

**Comment by Qianru69** [comment]
[issue #172 mock-up.pdf](https://github.com/freeCodeCamp/classroom/files/10475419/issue.172.mock-up.pdf)

Hi Utsab, here I uploaded my mock-up for this issue.
