### ISSUE TITLE
Remove mentions of localhost:3000 in our code

### ISSUE THREAD

**Issue by roberthuskins** [freeCodeCamp/classroom#174]
A lot of our code has references to localhost:3000. In certain places like the .env files it's fine to have this reference but any javascript files should not have localhost:3000 written because in production the port will be different. Any hardcoded links will also not link to correct spot in prod as well.

Anything written like `localhost:3000/classes` should be changed to `/classes`

**Comment by yashnerkar** [comment]
I would like to contribute on this issue

**Comment by roberthuskins** [comment]
Sure feel free to make a PR @yashnerkar
