### ISSUE TITLE
Dropdown menu doesn't show the full list on small screens

### ISSUE THREAD

**Issue by roberthuskins** [freeCodeCamp/classroom#184]
![image](https://user-images.githubusercontent.com/37780741/201414734-3b27d054-7e94-4789-811c-dd5c1f22201e.png)

People on small screens cannot see the full dropdown menu because the size of the modal is hard coded (presumably).

Users have a workaround in minimizing their screen, but this is not ideal.

**Comment by utsab** [comment]
Assigning this to Michelle Tan, Oswaldo Cortez, Fadi Buni
