### ISSUE TITLE
Config Next-Auth to allow account linking between different auth providers

### ISSUE THREAD

**Issue by GuillermoFloresV** [freeCodeCamp/classroom#219]
**Describe the bug**
Currently, if you have an account signed in using Google OAuth and you try to sign in using that same email, but through a different OAuth provider (Github), you are not allowed to sign in despite it being the same email. For ease of use, we want to enable account linking (so long as they are the same email under different Auth providers) for development experience only. 

Steps to reproduce: 
1. Must build locally (do **not** use the Gitpod setup)
2. Please use [this guide](https://docs.google.com/document/d/1apfjzfIwDAfg6QQf2KD1E1aeD-KU7DEllwnH9Levq4A/edit?usp=sharing) to set up the dev environment locally. 
3. Sign in and make an account using the Google provider option
4. Sign out 
5. Sign in to the Classroom App again using a different provider option, but make sure it still falls under the auth0 options (for example, Github).  The Github account must be associated with the same Gmail address as when you signed in on step 3.  (For example, your Gmail used in step 3 is `coolcoder123@gmail.com`, and your GitHub account also needs to have the email address:`coolcoder123@gmail.com`

Current Behavior: 
- Step 5 fails with an unclear error message: "Cannot verify identity" (I don't remember the exact error message).  

Desired Behavior: 
- Allow account linking between different providers but only for development experience. If the need arises (through user feedback), we can attempt to implement a much safer option for end-users to also have this experience.

This document also explains how to [reproduce](https://docs.google.com/document/d/1YvpDGDBD3u3un-ybPyb--UgSBX1UrhMWlRWYnNw5sgI/edit)

**Comment by rahulio96** [comment]
CTI Team U is working on this.
