### ISSUE TITLE
Certification drop-down menu remembers un-saved changes

### ISSUE THREAD

**Issue by Qianru69** [freeCodeCamp/classroom#238]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**To Reproduce**
1. Go to “Create class” or “Edit Class” page, and change the selections of certifications
2. Click on “Cancel”
3. Go back to the “Create class” or “Edit Class” page and open the drop-down certifications drop-down menu
4. The canceled changes are pre-selected.

**Expected behavior**
Make sure the Certifications drop-down shows the correct previously saved certifications selections

**Comment by utsab** [comment]
Assigning this issue to Diego Vega, Jason Chan, and Siyuan Zhai.
