### ISSUE TITLE
Documentation improvement: Add tech stack diagram and learning resources to the README

### ISSUE THREAD

**Issue by utsab** [freeCodeCamp/classroom#239]
We would like to add additional support materials to help new contributors become more familiar with the codebase: 
1. A description (ideally with a visual diagram) of the key technologies in the project's technology stack
2. A recommended sequence of learning resources someone can work through to get some experience with the tech stack. 

All of the information you need to answer the above two question is contained in this [slide deck](https://docs.google.com/presentation/d/1fDcT7NYy5ZAwpNkshVzKRDDQLTAWtu0mN0viJMJ-qEE/edit?usp=sharing).  For the tech stack diagram, look at slide 29.  For the learning resources, take a look at slides 36 - 51.  

For a model example of how an open source project can clearly document its technology stack, take a look at [Open Energy Dashboard](https://github.com/OpenEnergyDashboard/OED) (see the "Built with" section).  Then take a look at their more detailed [helper page](https://openenergydashboard.github.io/developer/learningTechnologies.html ) which lists out specific learning resources.

**Comment by utsab** [comment]
Assigning this issue to Diego Vega, Jason Chan, and Siyuan Zhai.

**Comment by adriangzz** [comment]
Hey @utsab the slide deck is private, could you take a look? Thanks

**Comment by akashthedeveloper** [comment]
Hii, @utsab I would like to contribute to this issue can you please assign it to me?

**Comment by Komal914** [comment]
Hey @utsab I can work on this if you would still like additional resources added to the read me file. There is a diagram added now but we are missing resources the tech stack like learning javascript for example. This issue is dated so I understand if this is not needed anymore.
