### ISSUE TITLE
Documentation improvement: Mention the style guide 

### ISSUE THREAD

**Issue by utsab** [freeCodeCamp/classroom#259]
We currently follow the freeCodeCamp style guide when styling the Classroom App: https://design-style-guide.freecodecamp.org/ 

Add a comment somewhere in README.md that documents the style guide.

**Comment by p2635** [comment]
Hi @utsab, I'm looking for good first issues so this is a great opportunity for me.  What wording would you be happy with for this improvement?

Suggestion:

# Contributing

## Style guide

Be sure to refer to the [freeCodeCamp style guide](https://github.com/freeCodeCamp/classroom) to ensure that this app is consistent with it. It contains information such as the Logo, Logo Colors, Typography etc.

**Comment by akashthedeveloper** [comment]
Hii, @utsab I am looking to contribute to this issue can you please assign it to me?

**Comment by zaidahmad25** [comment]
closes #294
