### ISSUE TITLE
/dashboard Page doesn't load

### ISSUE THREAD

**Issue by roberthuskins** [freeCodeCamp/classroom#306]
**Describe the bug**
/dashboard page does not load due to react version bump

**To Reproduce**
1.) Go to /dashboard page
2.) Table library has conflict with React 18

**Screenshots**
![image](https://user-images.githubusercontent.com/37780741/233860435-15043cc5-2118-44d0-8107-2fb43c044e23.png)

**Comment by utsab** [comment]
We deprecated the old /dashboard page.  Version 2 of the page is now live and running at the same URL (/dashboard).
