### ISSUE TITLE
Create seperate data processing function for class dashboard

### ISSUE THREAD

**Issue by GuillermoFloresV** [freeCodeCamp/classroom#328]
In order to eliminate the need to load the whole dashboard page to test components inside of it, we need to have the [data processing](https://github.com/freeCodeCamp/classroom/blob/main/components/dashtable_v2.js#L6-L97) that happens inside of the dashboard be a function (preferably in a new file) that we can simply import. This will help break down the code into more testable components.

The flow should look something like this:

1. Create a new file where our data processing code will live
2. Copy and paste the lines mentioned above from our dashboard page into this new file we created on step 1
3. Make sure the function is exported in the new file (so we can use it in our dashboard & tests)
4. Refactor the dashboard code to use the new function rather than code directly written inside of the dashboard page.

**Comment by ShubhamPatilsd** [comment]
CodeDay Labs students will be working on this

**Comment by theGaryLarson** [comment]
I'm working on this as part of CodeDay with my teammate Komal
