### ISSUE TITLE
/classes should take advantage of fast-refresh.

### ISSUE THREAD

**Issue by GuillermoFloresV** [freeCodeCamp/classroom#365]
**Describe the bug**
We currently are not taking advantage of refreshing our DOM when we create new classrooms and instead rely on reloading our page to see any changes in our UI. Making the data inside of our classes page rely on a state should help us solve that issue and remove the need to reload the page in order to see any new changes made to the UI.
**To Reproduce**
1. Go to `/classes`
2. Create, delete, or edit a classroom
3. Page must reload to see any changes to the DOM

**Expected behavior**
The DOM should refresh to show the new state of the `ClassInviteTable` component.

**Additional context**
Currently being worked on in #357

**Comment by lloydchang** [comment]
@Komal914 See above.
