### ISSUE TITLE
Need an architectural and systems design diagram for the freeCodeCamp classroom project

### ISSUE THREAD

**Issue by lloydchang** [freeCodeCamp/classroom#372]
**Describe the bug**
Need an architectural and systems design diagram for the freeCodeCamp classroom project

**To Reproduce**
1. Go to https://github.com/freeCodeCamp/classroom/
2. Read https://github.com/freeCodeCamp/classroom/#readme
3. Documentation references source code, but I don't see any architectural or system design diagrams
4. I could use an architectural and system design diagram based on the steps described in https://bit.ly/SystemDesignInterview

**Expected behavior**
An architectural and system design diagram hosted at https://excalidraw.com/ based on the steps described in https://bit.ly/SystemDesignInterview would be helpful to mentors like me.

**Additional context**
I am mentoring students working on freeCodeCamp/classroom and I am not understanding the architectural and system design of freeCodeCamp/classroom by reading https://github.com/freeCodeCamp/classroom/#readme — without diving deeper into the codebase.

**Comment by utsab** [comment]
HI @lloydchang, I'm glad you pointed out the lack of documentation for a system design diagram.  Thanks for providing the resources to create such a diagram.  As the project maintainer, I'll start working on this, or if one of your mentees is already planning to work on it, I'm happy to answer questions.

**Comment by lloydchang** [comment]
@utsab Thank you for being happy to answer questions!

Our CodeDay Labs student @Komal914 is interested in working on this issue.

Context: @Komal914 wrote in [CodeDay Labs Slack](https://codedayorg.slack.com/archives/C05ENB1VAKT/p1689495441158589?thread_ts=1689465005.250139):
> I would be happy to give this issue a try! I have never worked to create an architecture diagram for codebases, so I think it would be a great learning opportunity for me :blush:

Cc @sijin-raj @theGaryLarson @ngillux

**Comment by lloydchang** [comment]
Hi @utsab
Cc @GuillermoFloresV @ngillux @Komal914 @theGaryLarson @sijin-raj

[Question: Publicly, do you publish a prioritized list of GitHub issues for contributors work on?](https://codedayorg.slack.com/archives/C05ENB1VAKT/p1689539822914599?thread_ts=1689465005.250139&cid=C05ENB1VAKT)

@theGaryLarson [is having a hard time finding direction on what to work on within fcc/classroom repo.](https://codedayorg.slack.com/archives/C05E350DQH4/p1689288311856699)

Thank you!

**Comment by Komal914** [comment]
Hi! As @lloydchang said, I will be happy to work on this issue :)

**Comment by utsab** [comment]
HI @lloydchang -- We have an internal list of priorities which we have not yet translated into formal github issues.  I'll try to create a few more public issues by next week.  In the meantime, I assigned Issue #166 to @theGaryLarson.

**Comment by Komal914** [comment]
Hi @utsab, I am not sure exactly what the requirements are for this design. Here is the latest version of this design:

https://www.canva.com/design/DAFo8ezu7W8/EfUE0hjSDuJHFRGnG9NOvQ/edit?utm_content=DAFo8ezu7W8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Komal914** [comment]
![System Diagram](https://github.com/freeCodeCamp/classroom/assets/44416323/0e82da3c-bfdf-4c85-af98-a8ecd019a928)

**Comment by Komal914** [comment]
![System Diagram](https://github.com/freeCodeCamp/classroom/assets/44416323/96ef238b-07c0-424c-b0e2-c83b2d5eb77d)

**Comment by lloydchang** [comment]
lgtm

**Comment by lloydchang** [comment]
:shipit: :ship: :it:
