### ISSUE TITLE
Iteration happening on undefined data

### ISSUE THREAD

**Issue by Dmagical** [freeCodeCamp/classroom#374]
**Describe the bug**
During writing a test case in Jest it was revealed that there is some iteration happening on ‘undefined' data in dashtable_v2.js on the rawStudentSummary object.

**To Reproduce**
Unable to reproduce in the live codebase, the actual Jest test revealed the error.(Could be edge case or error boundary)

**Expected behavior**
There should be no undefined objects.

**Screenshots**
<img width="994" alt="Screen Shot 2023-07-17 at 12 36 40 PM" src="https://github.com/freeCodeCamp/classroom/assets/113726909/7749ea8a-5502-47da-a126-3199128d93be">

**Desktop (please complete the following information):**
Using codespaces.

**Comment by ngillux** [comment]
Working on fixing this.

**Comment by ngillux** [comment]
This should be resolved - it was a formatting issue when importing the data into the test file.
