### ISSUE TITLE
Use Generative AI tools to add and improve developer documentation for freeCodeCamp Classroom

### ISSUE THREAD

**Issue by lloydchang** [freeCodeCamp/classroom#391]
**Describe the issue**
Use Generative AI tools to add and improve developer documentation for freeCodeCamp Classroom.

**To Reproduce**
1. Mintlify Writer https://writer.mintlify.com/
2. Sourcegraph Code Search https://about.sourcegraph.com/code-search
3. Sourcegraph Cody https://docs.sourcegraph.com/cody
4. Genie, OpenAI ChatGPT, Visual Studio Code https://github.com/ai-genie/chatgpt-vscode
5. Additional Code Assistant Tools https://github.com/sourcegraph/awesome-code-ai

**Expected behavior**
Add and improve developer documentation for freeCodeCamp Classroom

**Additional context**
@theGaryLarson and I had a conversation via CodeDay Labs Slack:
- I suggested the above, and @theGaryLarson found the Generative AI tools such as Mintify Writer useful in helping @theGaryLarson, a developer, understand the codebase better.
```[tasklist]
### Tasks
```

**Comment by theGaryLarson** [comment]
I would like this assigned. I am currently working on issue #166 but am going to document the code base with mintlify and read through it to better understand the codebase.

**Comment by theGaryLarson** [comment]
Closed that draft PR and restarting fresh with the recent refactors to processing dashboard data.

**Comment by lloydchang** [comment]
Please contact @GuillermoFloresV if you have further questions about this. Thanks!

**Comment by lloydchang** [comment]
Closing this one because it's no longer needed.
