### ISSUE TITLE
Create a Details Component [1/4 Details component initial]

### ISSUE THREAD

**Issue by ngillux** [freeCodeCamp/classroom#425]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
Currently when a user views the details page it is an empty page. There should be a component created for the details page that is used instead of just a link to a blank page; i.e., details: <DetailComponent /> instead of details:  <a href={`/dashboard/v2/details/${props.classroomId}/` + `${studentName}`} >.

**To Reproduce**
1. Go to Classes
2. Click on 'View Class' then 'details'
3. See empty details page

**Expected behavior**
There should be a component that renders (can be blank for now).

**Comment by ngillux** [comment]
CodeDay mentees will be working on this.

**Comment by Komal914** [comment]
Hey @utsab I can work on this if you would still like additional resources added to the read me file. There is a diagram added now but we are missing resources the tech stack like learning javascript for example. This issue is dated so I understand if this is not needed anymore.
