### ISSUE TITLE
Create a Header component for the Details page [2/4 Details component initial]

### ISSUE THREAD

**Issue by ngillux** [freeCodeCamp/classroom#426]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
Currently when going to the details page it is blank. There should be a header with the students name and classroom presented instead. A screenshot has been provided on how the header should look.

**To Reproduce**
1. Go to Classes
2. Click on 'View class' then 'details'
3. See blank page

**Expected behavior**
There should be a more informative header (the one in the screenshot).

**Screenshots**
<img width="776" alt="Screenshot 2023-08-02 at 5 47 59 PM" src="https://github.com/freeCodeCamp/classroom/assets/20196901/fb031459-d719-4bfc-bf13-264e06527535">

**Comment by ngillux** [comment]
CodeDay mentees will be working on this.

**Comment by Komal914** [comment]
I will be working on this
