### ISSUE TITLE
Replace DataTable with useTable inside adminTable.js

### ISSUE THREAD

**Issue by Komal914** [freeCodeCamp/classroom#467]
**Describe the bug**
The DataTable library is being used inside the adminTable component. This library has caused issues in the past. It needs to be removed and replaced with useTable from react.

**To Reproduce**
1. Go to '../components/adminTable.js'
2. Remove line 2, and replace it with `import { useTable } from 'react-table'`
3. Scroll down to line 5. Update the rest of the code to work with useTable, and render.

**Additional context**
The library useTable has been used in the past inside '../components/dashtable_v2.js'. Refer to this file for example.

**Comment by Komal914** [comment]
I will be working on this.

**Comment by Ranjan-bej** [comment]
Is this issue still open??

**Comment by Komal914** [comment]
hey @Ranjan-bej, the issue is open but I am working on it. There should be a PR up soon.

**Comment by shootermv** [comment]
is this PR still under review?
